version: "3.9"

services:
  kcdb:
    image: postgres:16-alpine
    container_name: kcdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    depends_on:
      kcdb:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # --- Postgres config ---
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://kcdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      # Enable /health endpoints
      KC_HEALTH_ENABLED: "true"
      # Optional: increase logging if troubleshooting
      KC_LOG_LEVEL: INFO
    command:
      - start-dev
      - --import-realm
      - --hostname=keycloak         # ← add this
      - --hostname-port=8080        # ← add this
      - --hostname-strict=false
      - --http-enabled=true
      - --proxy=edge
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    healthcheck:
      # Use Keycloak's built-in health command (no curl/wget dependency)
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-health"]
      interval: 15s
      timeout: 10s
      retries: 60
      start_period: 60s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
